// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "9afa1b87a7d336f675d585f8e43c63baec2f715b5c8e2ea4d0824607af5e07ff")
