// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "b6e98a30a3cfc50a0a4fdd4a533cb0e634f07d0aa11d6840f8617a443fec8946")
