// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "637ee33295d029593e4b86fe19189a404ae1ec17714622740fa39cc572bfc7c9")
